/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String[] args) {
        String s = "ABCD";
        for (int i = 0; i < s.length(); i++) {
            char prefix = s.charAt(i);
            String rest = s.substring(0, i) + s.substring(i + 1, s.length());
            System.out.println(prefix + ":" + rest);
        }
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
